platform :ios, '11.0'
source = 'https://github.com/rwbutler/LetterCase'
use_frameworks!

target 'TypographyKit_Example' do
  pod 'TypographyKit', :path => '../'

  target 'TypographyKit_Tests' do
    inherit! :search_paths

    
  end
end
